# Pre-commit hooks configuration for Vietnamese AI Dubbing
# Install: pre-commit install
# Run: pre-commit run --all-files

repos:
  # Black - Python code formatter
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]

  # isort - Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black, --filter-files]

  # Flake8 - Style guide enforcement
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203,W503]

  # MyPy - Static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args: [--ignore-missing-imports]

  # Pylint - Code analysis
  - repo: https://github.com/pycqa/pylint
    rev: v2.17.5
    hooks:
      - id: pylint
        args: [--rcfile=.pylintrc]
        files: \.py$

  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-ast
      - id: check-docstring-first
      - id: mixed-line-ending
        args: [--fix=lf]

  # TypeScript/JavaScript formatting (for frontend)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        types: [javascript, typescript, css, json, yaml, markdown]
        exclude: ^(node_modules|\.git)

  # ESLint (for frontend)
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.45.0
    hooks:
      - id: eslint
        types: [javascript, typescript]
        additional_dependencies:
          - eslint@8.45.0
          - "@typescript-eslint/eslint-plugin@6.0.0"
          - "@typescript-eslint/parser@6.0.0"
          - eslint-config-prettier@9.0.0
        exclude: ^(node_modules|\.git)

  # Check for secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package-lock.json

  # Check for TODO/FIXME comments
  - repo: local
    hooks:
      - id: check-todos
        name: check-todos
        entry: python -m pytest tests/ -v
        language: system
        files: \.(py|js|ts)$
        pass_filenames: false